name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Run tests
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macOS-latest]

    steps:
    # check-out repo and set-up python
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # install poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1
    # install dependencies
    - name: Install dependencies
      run: poetry install --no-interaction
    # run tests
    - name: Run tests
      run: poetry run pytest -v

  # Linting, formatting, type-checking, etc.
  lint:
    runs-on: ubuntu-latest

    steps:
    # check-out repo and set-up python
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    # install poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1
    # install dependencies
    - name: Install dependencies
      run: poetry install --no-interaction
    # run pre-commit hooks
    - name: Run formatting hook
      run: poetry run pre-commit run black --all-files
    - name: Run linting hook
      run: poetry run pre-commit run ruff --all-files
    - name: Run type-checking hook
      run: poetry run pre-commit run mypy --all-files
